target:test

test: main.cpp Abstract.cpp Abstract.h Vector.cpp Vector.h Cell.h Array_1d.cpp Array_1d.h Adapter.cpp Adapter.h
	g++ main.cpp Abstract.cpp Vector.cpp Array_1d.cpp Adapter.cpp -std=c++11
	./a.out
